version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: /path/to/day14/simple-python-app/stop-container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /path/to/day14/simple-python-app/start-container.sh
      timeout: 300
      runas: root
