version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r day14/simple-python-app/requirements.txt  # Install dependencies from requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - cd day14/simple-python-app/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - docker build -t "$DOCKER_REGISTRY_USERNAME/my_flask_app:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/my_flask_app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
